package com.vasensio.conecta4.classes

enum class KeyValues (val value : String) {
    K_SET_PLAYER_NAME("setPlayerName"),
    K_TYPE("type"),
    K_NAME("name"),
    K_CLIENT_NAME("clientName"),
    K_VALUE("value"),
    K_SERVER_DATA("serverData"),
    K_COLOR("color"),
    K_PLAY("play"),
    K_CLIENT_LIST("clientsList"),
    K_CLIENTS_LIST("clientsList"),
    K_COUNTDOWN("countdown"),
    K_CLIENT_SEND_INVITATION("clientSendInvitation"),
    K_CLIENT_ANSWER_INVITATION("clientAnswerInvitation"),
    K_SEND_TO("sendTo"),
    K_SEND_FROM("sendFrom"),
    K_PIECE_ID("pieceId"),
    K_REASON("reason"),
    K_PLAY_ACCEPTED("playAccepted"),
    K_PLAY_REJECTED("playRejected"),
    K_WINNING_LINE_COORDS("winningLineCoords"),
    K_OBJECT_LIST("objectsList"),
    K_COLUMN("column"),
    K_ROW("row"),
    K_WINNER("winner"),
    K_GAME_ENDED("gameEnded"),
    K_PLAYER_TURN("playerTurn"),
    K_CLIENT_REQUEST_PLAY("clientRequestPlay"),
    K_CLIENT_DISCONNECTED("clientDisconnected")
}